# Generated by Django 6.0.7 on 2026-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('shift',), name='one_confirmed_booking_per_shift'),
        ),
    ]
