# Generated by Django 6.0.7 on 2026-07-30 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_one_confirmed_booking_per_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='bill_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shift',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='shift_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('pay_rate__gte', 0)), name='shift_pay_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('bill_rate__gte', 0)), name='shift_bill_rate_nonnegative'),
        ),
    ]
