# Generated by Django 6.0.7 on 2026-07-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_shift_bill_rate_alter_shift_pay_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='home_area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='home_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='legacy_mysql_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='legacy_mysql_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profession',
            name='legacy_mysql_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FacilityExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_shift_count', models.PositiveIntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_worked_on', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_experiences', to='bookings.candidate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_experiences', to='bookings.client')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_experiences', to='bookings.profession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'client', 'profession'), name='unique_candidate_facility_role_experience')],
            },
        ),
    ]
