# Generated by Django 6.0.7 on 2026-07-30 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAccessPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_ts', models.BooleanField(default=False)),
                ('link_ts', models.BooleanField(default=False)),
                ('approve_ts', models.BooleanField(default=False)),
                ('export_ts', models.BooleanField(default=False)),
                ('link_conf', models.BooleanField(default=False)),
                ('export_inv', models.BooleanField(default=False)),
                ('edit_clients', models.BooleanField(default=False)),
                ('edit_cand', models.BooleanField(default=False)),
                ('edit_cons', models.BooleanField(default=False)),
                ('update_client_rates', models.BooleanField(default=False)),
                ('update_cand_rates', models.BooleanField(default=False)),
                ('override_can_rates', models.BooleanField(default=False)),
                ('man_users', models.BooleanField(default=False)),
                ('view_cons_report', models.BooleanField(default=False)),
                ('view_client_report', models.BooleanField(default=False)),
                ('view_can_report', models.BooleanField(default=False)),
                ('view_com_report', models.BooleanField(default=False)),
                ('view_profit_report', models.BooleanField(default=False)),
                ('submit_cand_live', models.BooleanField(default=False)),
                ('delete_files', models.BooleanField(default=False)),
                ('set_compliance', models.BooleanField(default=False)),
                ('assign_cons', models.BooleanField(default=False, null=True)),
                ('legacy_mysql_id', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_ts', models.BooleanField(default=False)),
                ('link_ts', models.BooleanField(default=False)),
                ('approve_ts', models.BooleanField(default=False)),
                ('export_ts', models.BooleanField(default=False)),
                ('link_conf', models.BooleanField(default=False)),
                ('export_inv', models.BooleanField(default=False)),
                ('edit_clients', models.BooleanField(default=False)),
                ('edit_cand', models.BooleanField(default=False)),
                ('edit_cons', models.BooleanField(default=False)),
                ('update_client_rates', models.BooleanField(default=False)),
                ('update_cand_rates', models.BooleanField(default=False)),
                ('override_can_rates', models.BooleanField(default=False)),
                ('man_users', models.BooleanField(default=False)),
                ('view_cons_report', models.BooleanField(default=False)),
                ('view_client_report', models.BooleanField(default=False)),
                ('view_can_report', models.BooleanField(default=False)),
                ('view_com_report', models.BooleanField(default=False)),
                ('view_profit_report', models.BooleanField(default=False)),
                ('submit_cand_live', models.BooleanField(default=False)),
                ('delete_files', models.BooleanField(default=False)),
                ('set_compliance', models.BooleanField(default=False)),
                ('assign_cons', models.BooleanField(default=False, null=True)),
                ('legacy_mysql_id', models.PositiveIntegerField(unique=True)),
                ('access_type', models.PositiveIntegerField(default=0)),
                ('assigned_desk', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='bookings.legacyaccesspreset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
