# Generated by Django 6.0.7 on 2026-07-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_legacyaccesspreset_legacyuserprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'permissions': [('manage_bookings', 'Can create, update and delete bookings')]},
        ),
    ]
