# Generated by Django 6.0.7 on 2026-07-31 07:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_vacancy_shift_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfessionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bill_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_rates', to='bookings.profession')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_rates', to='bookings.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'profession'), name='unique_rate_per_site_profession')],
            },
        ),
    ]
