# Generated by Django 6.0.7 on 2026-07-31 09:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_siteprofessionrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfessionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_mysql_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bill_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_rates', to='bookings.client')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rates', to='bookings.profession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'profession'), name='unique_rate_per_client_profession')],
            },
        ),
    ]
