# Generated by Django 6.0.7 on 2026-08-03 13:55

from django.db import migrations, models


def validate_nonnegative_rates(apps, schema_editor):
    rate_model = apps.get_model("bookings", "ClientProfessionRate")
    has_negative_rates = rate_model.objects.filter(
        models.Q(pay_rate__lt=0) | models.Q(bill_rate__lt=0)
    ).exists()
    if has_negative_rates:
        raise RuntimeError(
            "Cannot install rate constraints while negative legacy rates exist. "
            "Correct those source records and rerun the migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_mfadevice'),
    ]

    operations = [
        migrations.RunPython(
            validate_nonnegative_rates,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='clientprofessionrate',
            constraint=models.CheckConstraint(condition=models.Q(('pay_rate__gte', 0)), name='client_profession_pay_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='clientprofessionrate',
            constraint=models.CheckConstraint(condition=models.Q(('bill_rate__gte', 0)), name='client_profession_bill_rate_nonnegative'),
        ),
    ]
