# Generated by Django 6.0.7 on 2026-08-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_candidatechangeaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='bookings.department'),
        ),
        migrations.AddField(
            model_name='client',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='clients', to='bookings.department'),
        ),
    ]
