# Generated by Django 6.0.7 on 2026-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_candidate_departments_client_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assigned_consultant',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidate',
            name='citizenship_status',
            field=models.CharField(blank=True, choices=[('citizen', 'South African citizen'), ('permanent_resident', 'Permanent resident'), ('refugee', 'Refugee')], max_length=24),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidate',
            name='criminal_check',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='division',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='drivers_license',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidate',
            name='employment_equity',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fingerprint_status',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='home_language',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidate',
            name='home_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='candidate',
            name='identity_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_locum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_sa_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='marital_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidate',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_contact',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='owns_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='passport_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='candidate',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='qualification',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidate',
            name='qualification_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('unspecified', 'Unspecified')], max_length=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='sex_source',
            field=models.CharField(blank=True, choices=[('legacy', 'Legacy'), ('manual', 'Manual'), ('sa_id', 'South African ID')], max_length=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidate',
            name='visa_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='visa_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='visa_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='visa_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='CandidateProfileOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('country', 'Country'), ('visa_type', 'Visa type'), ('language', 'Language'), ('division', 'Division'), ('consultant', 'Consultant'), ('gender', 'Gender'), ('employment_equity', 'Employment equity'), ('education_level', 'Education level'), ('qualification', 'Qualification'), ('qualification_type', 'Qualification type'), ('source', 'Source'), ('marital_status', 'Marital status'), ('drivers_license', "Driver's licence"), ('fingerprint_status', 'Fingerprint status'), ('criminal_check', 'Criminal check'), ('province', 'Province'), ('suburb', 'Suburb')], max_length=32)),
                ('legacy_mysql_id', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=160)),
                ('parent_legacy_mysql_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'label', 'legacy_mysql_id'],
                'constraints': [models.UniqueConstraint(fields=('category', 'legacy_mysql_id'), name='unique_candidate_profile_option')],
            },
        ),
    ]
