# Generated by Django 6.0.7 on 2026-08-26 05:31

import bookings.models
import bookings.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_mfatrustedbrowser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('declined', 'Declined'), ('approved', 'Approved'), ('void', 'Void')], default='draft', max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('payroll_exported_at', models.DateTimeField(blank=True, null=True)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet', to='bookings.booking')),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_timesheets', to=settings.AUTH_USER_MODEL)),
                ('declined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
                'permissions': [('capture_timesheet', 'Can capture timesheets'), ('approve_timesheet', 'Can approve or decline timesheets'), ('export_payroll', 'Can generate payroll exports'), ('generate_invoice', 'Can generate invoices'), ('export_accounting', 'Can generate accounting exports')],
            },
        ),
        migrations.CreateModel(
            name='TimesheetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('source', 'Signed timesheet'), ('client_confirmation', 'Client confirmation / motivation')], default='source', max_length=32)),
                ('file', models.FileField(storage=bookings.storage.PrivateFileSystemStorage(), upload_to=bookings.models.timesheet_document_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='bookings.timesheet')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_timesheet_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start', models.DateTimeField()),
                ('actual_end', models.DateTimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('rate_category', models.CharField(choices=[('normal', 'Normal / day'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('overtime', 'Overtime'), ('standby', 'Standby'), ('night', 'Night'), ('public_holiday', 'Public holiday')], default='normal', max_length=24)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='bookings.timesheet')),
            ],
            options={
                'ordering': ['actual_start', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('actual_end__gt', models.F('actual_start'))), name='timesheet_line_ends_after_start'), models.CheckConstraint(condition=models.Q(('pay_rate__gte', 0)), name='timesheet_line_pay_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('bill_rate__gte', 0)), name='timesheet_line_bill_rate_nonnegative')],
            },
        ),
    ]
