# Generated by Django 6.0.7 on 2026-08-26 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_timesheet_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='payroll_code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='accounting_code',
            field=models.CharField(blank=True, help_text='Pastel Customer/account code used for finance exports.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payroll_job_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='requires_timesheet_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FinanceExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payroll', 'Payroll'), ('pastel_sales', 'Pastel sales'), ('pastel_credit', 'Pastel credit notes')], max_length=24)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('upload_confirmed', 'External upload confirmed'), ('void', 'Void')], default='generated', max_length=24)),
                ('process_code', models.CharField(max_length=80)),
                ('file_name', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('upload_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_finance_exports', to=settings.AUTH_USER_MODEL)),
                ('timesheets', models.ManyToManyField(blank=True, related_name='export_batches', to='bookings.timesheet')),
                ('upload_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_finance_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
    ]
