# Generated by Django 6.0.7 on 2026-08-26 05:38

import bookings.models
import bookings.storage
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_finance_export_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('sales_contra_account', models.CharField(default='4000', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finance setting',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('invoice_date', models.DateField()),
                ('client_name', models.CharField(max_length=200)),
                ('accounting_code', models.CharField(max_length=40)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('document', models.FileField(blank=True, storage=bookings.storage.PrivateFileSystemStorage(), upload_to=bookings.models.invoice_document_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pastel_exported_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bookings.client')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='financeexportbatch',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='export_batches', to='bookings.invoice'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_number', models.CharField(max_length=80)),
                ('candidate_name', models.CharField(max_length=220)),
                ('description', models.CharField(max_length=255)),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='bookings.invoice')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='bookings.timesheet')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
