# Generated by Django 6.0.7 on 2026-08-26 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_invoices_and_pastel_exports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexportbatch',
            name='sha256',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='timesheetdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('timesheet', 'kind'), name='one_current_document_per_timesheet_kind'),
        ),
    ]
