# Generated by Django 6.0.7 on 2026-08-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_finance_workflow_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='invoice_issuer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='invoice_issuer_legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='invoice_issuer_vat_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_billing_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_vat_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_legal_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_vat_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
