# Generated by Django 6.0.7 on 2026-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_invoice_legal_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetline',
            name='rate_category',
            field=models.CharField(choices=[('normal', 'Normal / day'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('overtime', 'Overtime'), ('standby', 'Standby'), ('night', 'Night'), ('public_holiday', 'Public holiday'), ('standby_holiday', 'Standby Holiday'), ('standby_sunday', 'Standby Sunday'), ('standby_week', 'Standby Week')], default='normal', max_length=24),
        ),
    ]
