# Generated by Django 6.0.7 on 2026-08-26 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_stage_timesheets_for_payroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=16)),
                ('body', models.TextField()),
                ('customer_id', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('accepted', 'Accepted by provider'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_event_id', models.CharField(blank=True, max_length=80)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation_sms', to='bookings.booking')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_messages', to='bookings.candidate')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'permissions': [('send_booking_sms', 'Can queue booking confirmation SMS messages')],
            },
        ),
    ]
