# Generated by Django 6.0.7 on 2026-08-31 11:45

import django.db.models.deletion
from django.db import migrations, models


def seed_approved_regions(apps, schema_editor):
    Region = apps.get_model('bookings', 'Region')
    Region.objects.bulk_create([
        Region(code='WC', name='Western Cape'),
        Region(code='NC', name='Northern Cape'),
        Region(code='NW', name='North West'),
        Region(code='FS', name='Free State'),
        Region(code='GAU', name='Gauteng'),
        Region(code='EC', name='Eastern Cape'),
        Region(code='KZN', name='KwaZulu-Natal'),
        Region(code='MPUM', name='Mpumalanga'),
        Region(code='LIMPOPO', name='Limpopo'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0035_legacy_user_booking_access_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_approved_regions, migrations.RunPython.noop),
        migrations.CreateModel(
            name='RegionalDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_desks', to='bookings.department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_desks', to='bookings.region')),
            ],
            options={
                'ordering': ['region__name', 'department__legacy_mysql_id'],
            },
        ),
        migrations.CreateModel(
            name='RegionalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_clients', to='bookings.client')),
                ('regional_desk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_clients', to='bookings.regionaldesk')),
            ],
            options={
                'ordering': ['regional_desk__region__name', 'regional_desk__department__legacy_mysql_id', 'client__name'],
            },
        ),
        migrations.CreateModel(
            name='RegionalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('regional_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_facilities', to='bookings.regionalclient')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_facilities', to='bookings.site')),
            ],
            options={
                'ordering': ['regional_client__regional_desk__region__name', 'regional_client__client__name', 'site__name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('regional_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='bookings.regionalfacility')),
            ],
            options={
                'ordering': ['regional_facility__site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateWardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_memberships', to='bookings.candidate')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_memberships', to='bookings.ward')),
            ],
            options={
                'ordering': ['ward__name', 'candidate__first_name', 'candidate__last_name'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='wards',
            field=models.ManyToManyField(blank=True, related_name='candidates', through='bookings.CandidateWardMembership', to='bookings.ward'),
        ),
        migrations.AddConstraint(
            model_name='regionaldesk',
            constraint=models.UniqueConstraint(fields=('region', 'department'), name='unique_desk_per_region'),
        ),
        migrations.AddConstraint(
            model_name='regionalclient',
            constraint=models.UniqueConstraint(fields=('regional_desk', 'client'), name='unique_client_per_regional_desk'),
        ),
        migrations.AddConstraint(
            model_name='regionalfacility',
            constraint=models.UniqueConstraint(fields=('regional_client', 'site'), name='unique_facility_per_regional_client'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('regional_facility', 'name'), name='unique_ward_per_regional_facility'),
        ),
        migrations.AddConstraint(
            model_name='candidatewardmembership',
            constraint=models.UniqueConstraint(fields=('candidate', 'ward'), name='unique_candidate_ward_membership'),
        ),
    ]
