# Generated by Django 6.0.7 on 2026-08-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_region_regionaldesk_regionalclient_regionalfacility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'permissions': [('manage_bookings', 'Can create, update and delete bookings'), ('view_candidate_pay_rates', 'Can view Candidate pay rates'), ('view_client_charge_rates', 'Can view Client charges and profitability'), ('override_approved_rates', 'Can override approved rates')]},
        ),
    ]
