"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() in {'1', 'true', 'yes'}

# SECURITY WARNING: keep the secret key used in production secret!
configured_secret_key = os.getenv('DJANGO_SECRET_KEY')
if not DEBUG and not configured_secret_key:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY is required when DEBUG is false.')
SECRET_KEY = configured_secret_key or secrets.token_urlsafe(50)


def development_mfa_key():
    key_path = BASE_DIR / '.mfa-dev-key'
    try:
        return key_path.read_text(encoding='utf-8').strip()
    except FileNotFoundError:
        generated_key = secrets.token_urlsafe(50)
        try:
            descriptor = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError:
            return key_path.read_text(encoding='utf-8').strip()
        with os.fdopen(descriptor, 'w', encoding='utf-8') as key_file:
            key_file.write(generated_key)
        return generated_key

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'bookings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'bookings.mfa_assurance.MfaAssuranceMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'immploy_locum'),
        'USER': os.getenv('POSTGRES_USER', 'pierreb'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', ''),
        'PORT': os.getenv('POSTGRES_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'bookings.authentication.CaseInsensitiveModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-za'

TIME_ZONE = 'Africa/Johannesburg'

MFA_ISSUER_NAME = os.getenv('DJANGO_MFA_ISSUER_NAME', 'IMMploy Locum Booking')
MFA_TRUSTED_LAN_NETWORKS = [
    network.strip()
    for network in os.getenv('DJANGO_MFA_TRUSTED_LAN_NETWORKS', '').split(',')
    if network.strip()
]
MFA_TRUSTED_PROXY_NETWORKS = [
    network.strip()
    for network in os.getenv(
        'DJANGO_MFA_TRUSTED_PROXY_NETWORKS', '127.0.0.0/8,::1/128'
    ).split(',')
    if network.strip()
]
MFA_TRUSTED_BROWSER_MAX_AGE_SECONDS = int(
    os.getenv('DJANGO_MFA_TRUSTED_BROWSER_MAX_AGE_SECONDS', str(30 * 24 * 60 * 60))
)
configured_mfa_encryption_key = os.getenv('DJANGO_MFA_ENCRYPTION_KEY')
if DEBUG:
    MFA_ENCRYPTION_KEY = configured_mfa_encryption_key or development_mfa_key()
elif not configured_mfa_encryption_key:
    raise ImproperlyConfigured(
        'DJANGO_MFA_ENCRYPTION_KEY is required when DEBUG is false.'
    )
else:
    MFA_ENCRYPTION_KEY = configured_mfa_encryption_key

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.getenv('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles'))
PRIVATE_MEDIA_ROOT = Path(
    os.getenv('DJANGO_PRIVATE_MEDIA_ROOT', BASE_DIR / 'private-media')
)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LEGACY_MYSQL_CONFIG = os.getenv(
    'LEGACY_MYSQL_CONFIG',
    str(BASE_DIR.parent.parent / 'timesheet_db_config.json') if DEBUG else '',
)
SMS_MYMOBILEAPI_BASE_URL = os.getenv(
    "SMS_MYMOBILEAPI_BASE_URL",
    "https://rest.mymobileapi.com",
)
SMS_MYMOBILEAPI_CLIENT_ID = os.getenv("SMS_MYMOBILEAPI_CLIENT_ID", "")
SMS_MYMOBILEAPI_SECRET = os.getenv("SMS_MYMOBILEAPI_SECRET", "")
CORS_ALLOWED_ORIGINS = ['http://localhost:5173', 'http://127.0.0.1:5173']
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173' if DEBUG else '',
    ).split(',')
    if origin.strip()
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
}

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv(
        'DJANGO_SECURE_SSL_REDIRECT', 'true'
    ).lower() in {'1', 'true', 'yes'}
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    if os.getenv('DJANGO_TRUST_PROXY_HEADERS', 'false').lower() in {'1', 'true', 'yes'}:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
